name: Build LLVM Obfuscator

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-obfuscator:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build python3 g++ git

    - name: Clone LLVM Obfuscator (llvm-4.0 branch)
      run: |
        git clone --depth=1 --branch llvm-4.0 https://github.com/obfuscator-llvm/obfuscator.git obf-src

    - name: Build LLVM with obfuscation
      run: |
        mkdir build
        cd build
        cmake ../obf-src -G Ninja -DCMAKE_BUILD_TYPE=Release
        ninja

    - name: Upload Clang Obfuscator Binaries
      uses: actions/upload-artifact@v4
      with:
        name: clang-obf
        path: build/bin/
