name: Build Obfuscator LLVM 4.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build g++ python3 zlib1g-dev libedit-dev libncurses5-dev libxml2-dev libffi-dev swig doxygen

    - name: Create Build Directory
      run: mkdir llvm-build

    - name: Configure with CMake
      working-directory: llvm-build
      run: |
        cmake ../obf-src \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_INCLUDE_TESTS=OFF \
          -DLLVM_ENABLE_OCAMLDOC=OFF \
          -DLLVM_TARGETS_TO_BUILD="X86" \
          -DLLVM_ENABLE_PROJECTS="clang"

    - name: Build with Ninja
      working-directory: llvm-build
      run: ninja

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: obfuscator-llvm
        path: llvm-build/bin/
